language: java
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

cache:
  apt: true
  directories:
    - $HOME/.m2

sudo: required

addons:
  apt:
    packages:
    - jq

matrix:
  allow_failures:
    - jdk: oraclejdk9

script:
  #run tests and integration tests
  # see  https://stackoverflow.com/questions/34405047/how-do-you-merge-into-another-branch-using-travis-with-git-commands
  - build_head=$(git rev-parse HEAD) 
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch origin $TRAVIS_BRANCH
  - git checkout -f $TRAVIS_BRANCH
  - git checkout $build_head
  - git merge $TRAVIS_BRANCH
  - mvn integration-test -Dlogging-level=INFO
  #run jar sanity tests
  - VERSION=$(mvn help:evaluate -Dexpression=project.version | grep -E '^[0-9.]+')
  - echo $VERSION

  after_success:
  #codacy-coverage send report. Uses Travis Env variable (CODACY_PROJECT_TOKEN)
  - test $TRAVIS_PULL_REQUEST = "false" && test $TRAVIS_JDK_VERSION = "oraclejdk8" && wget -O codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
  - test $TRAVIS_PULL_REQUEST = "false" && test $TRAVIS_JDK_VERSION = "oraclejdk8" && java -jar codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml
